version: "3.9"

services:
  portfolio-cms:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    container_name: portfolio-cms
    ports:
      - "7000:8080"
    env_file: .env
    environment:
      MONGO_URI: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASS}@mongodb:${MONGO_DB_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - wedding_network

networks:
  wedding_network:
    external: true

